# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Use `[]` not `[ ]`
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Use `'foo'` not `"foo"` unless escaping is required
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Include:
    - "app/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "test/**/*"
    - "Gemfile"
