default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: delta_green_development

test:
  <<: *default
  database: delta_green_test

production:
  primary: &primary_production
    <<: *default
    database: delta_green_production
    username: delta_green
    password: <%= ENV["DELTA_GREEN_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: delta_green_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: delta_green_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: delta_green_production_cable
    migrations_paths: db/cable_migrate
